[build]
  command = "cd netlify/functions && npm install && cd ../../frontend && npm install && npm run build"
  publish = "frontend/dist"
  functions = "netlify/functions"

[dev]
  command = "cd frontend && npm run dev"
  port = 3000
  targetPort = 3000
  framework = "#custom"

[[redirects]]
  from = "/api/resume/upload"
  to = "/.netlify/functions/resume"
  status = 200

[[redirects]]
  from = "/api/job/add"
  to = "/.netlify/functions/job"
  status = 200

[[redirects]]
  from = "/api/speech/transcribe"
  to = "/.netlify/functions/speech"
  status = 200

[[redirects]]
  from = "/api/answer/generate"
  to = "/.netlify/functions/answer"
  status = 200

[functions]
  node_bundler = "esbuild"
